### ISSUE TITLE
Alter size based on content

### ISSUE THREAD

**Issue by syphernl** [nikku/jquery-bootstrap-scripting#10]
It would be nice if we could alter the size of the modal box, based on the (ajax) content. The default Bootstrap width is 560px, which is not wide enough in some cases.

**Comment by nikku** [comment]
Do you think this is desirable? I would suggest to use a normal webpage to display extra large content, e.g. tables.

**Comment by syphernl** [comment]
Well, maybe make it optional or add a max-width to it. 

In my case I had to widen the default modals because they were not wide enough for a simple form element row: "{label} {input field} {fairly long suffix that was too wide by default}". 

I believe Facebox does the same thing. I was using this prior to finding this library (after spending 1-2h on making it work with Bootstrap :-))

**Comment by nikku** [comment]
Well, it is rather easy to change that, maybe consider to do it on your own. Override the boostrap styles for `.modal` which are

``` css
.modal {
    ...
    width: 560px;
    top: 50%;
    margin: -250px 0 0 -250px;
}
```

with your new styles for wide dialogs 

``` css
.wide-modal {
    ...
    top: 20%;
    width: 800px;
    margin: 0 0 0 -400px; /* -1 * (width / 2) */ 
}
```
